// Generated by make-ip-conf.pl
// eth1 166.111.70.6 00:27:19:94:70:60
// eth2 166.111.70.7 00:e0:4c:00:00:af

// Shared IP input path and routing table
ip :: Strip(14)
    -> CheckIPHeader(INTERFACES 166.111.70.6/255.255.255.0 166.111.70.7/255.255.255.0)
    -> rt :: StaticIPLookup(
	166.111.70.6/32 0,
	166.111.70.255/32 0,
	166.111.70.0/32 0,
	166.111.70.7/32 0,
	166.111.70.255/32 0,
	166.111.70.0/32 0,
	166.111.70.0/255.255.255.0 1,
	166.111.70.0/255.255.255.0 2,
	255.255.255.255/32 0.0.0.0 0,
	0.0.0.0/32 0,
	166.111.70.11/255.255.255.255  2,
	166.111.70.12/255.255.255.255  1,
	0.0.0.0/0.0.0.0 166.111.70.1 1);

// ARP responses are copied to each ARPQuerier and the host.
arpt :: Tee(3);

// Input and output paths for eth1
c0 :: Classifier(12/0806 20/0001, 12/0806 20/0002, 12/0800, -);
FromDevice(eth1) ->  c0;
out0 :: Queue(200) -> todevice0 :: ToDevice(eth1);
c0[0] ->  ar00 :: ARPResponder(166.111.70.6 166.111.70.0/24 00:27:19:94:70:60) -> out0;
arpq0 :: ARPQuerier(166.111.70.6, 00:27:19:94:70:60) -> out0;
c0[1] ->  arpt;
arpt[0] -> [1]arpq0;
c0[2] ->  Paint(1) -> ip;
c0[3] ->  Discard;

// Input and output paths for eth2
// Print(time,24,CONTENTS ASCII, TIMESTAMP true) ->  //Be careful, adding any element will cause new RAT!!!!
c1 :: Classifier(12/0806 20/0001, 12/0806 20/0002, 12/0800, -);
FromDevice(eth2) -> c1;
out1 :: Queue(200) -> todevice1 :: ToDevice(eth2);
c1[0] -> ar1 :: ARPResponder(166.111.70.7 166.111.70.0/24 00:e0:4c:00:00:af) -> out1;
arpq1 :: ARPQuerier(166.111.70.7, 00:e0:4c:00:00:af) -> out1;
c1[1] -> arpt;
arpt[1] -> [1]arpq1;
c1[2] -> Paint(2) -> ip;
c1[3] ->  Discard;

// Local delivery
//toh :: ToHost;
//arpt[2] -> toh;
//rt[0] -> EtherEncap(0x0800, 1:1:1:1:1:1, 2:2:2:2:2:2) -> toh;
arpt[2] ->  Discard;
rt[0] -> EtherEncap(0x0800, 1:1:1:1:1:1, 2:2:2:2:2:2) ->  Discard;

// Forwarding path for eth1
rt[1] -> DropBroadcasts
    -> cp0 :: PaintTee(1)
    -> gio0 :: IPGWOptions(166.111.70.6)
    -> FixIPSrc(166.111.70.6)
    -> dt0 :: DecIPTTL
    -> fr0 :: IPFragmenter(1500)
    -> [0]arpq0;
dt0[1] -> ICMPError(166.111.70.6, timeexceeded) -> rt;
fr0[1] -> ICMPError(166.111.70.6, unreachable, needfrag) -> rt;
gio0[1] -> ICMPError(166.111.70.6, parameterproblem) -> rt;
cp0[1] -> ICMPError(166.111.70.6, redirect, host) -> rt;

// Forwarding path for eth2
rt[2] ->  DropBroadcasts
    -> cp1 :: PaintTee(2)
    -> gio1 :: IPGWOptions(166.111.70.7)
    -> FixIPSrc(166.111.70.7)
    -> dt1 :: DecIPTTL
    -> fr1 :: IPFragmenter(1500)
    -> [0]arpq1;
dt1[1] -> ICMPError(166.111.70.7, timeexceeded) -> rt;
fr1[1] -> ICMPError(166.111.70.7, unreachable, needfrag) -> rt;
gio1[1] -> ICMPError(166.111.70.7, parameterproblem) -> rt;
cp1[1] -> ICMPError(166.111.70.7, redirect, host) -> rt;
